<?
$seq1 = "AABABAQADJFCBAKRGMOSAIDFGABBBACDJFAACAAABBAMSDVPBABACCJFGJMFBABB";
$seq2 = "GGABBBMEMJACBBDMQNPMDKABAAAABAAGCDJBCACBAAABAAEXKPBCBBADJARJMFBBAB";
$matfile = "./SM/BLOSUM-like_scoring_matrix";
$opp = "-6";
$exp = "-3";
$suboptimal = "10";
?>