<?php
$seq1="uuXu'ZCXAXX({f8uu'wOCw)XwXX";
$arc1="((((.(.((((....))))..).))))";
$seq2="OOuuXzxXXwUACuwX'OuAXuw'uuvAvU9wu'wv'uuA";
$arc2="......(((....)))........................";
$matfile="SM/23-4L_matrix";
$opp="-9";
$exp="-1";
$suboptimal="1";
?>
