<?
$seq1 = "AABABAQADJFCBAKRGMOSAIDFGABBBACDJFAACAAABBAMSDVPBABACCJFGJMFBABBABABBAHKLHH";
$seq2 = "GGABBBMEMJACBBDMQNPMDKABAAAABAAGCDJBCACBAAABAAEXKPBCBBADJARJMFBBABCBBAABCQCGG";
$matfile = "./SM/BLOSUM-like_scoring_matrix";
$opp = "-6";
$exp = "-2";
$suboptimal = "10";
?>