<?php
$seq1="uuYAC'3JPxXwYuZBZw''xXX";
$arc1=".......................";
$seq2="**'uX)6D29'uXCXAXAuXCC)";
$arc1=".......................";
$matfile="SM/23-4L_matrix";
$opp="0";
$exp="-1";
$suboptimal="1";
?>
