<?php
$seq1="AABABAQADJFCBAKRGMOSAI";
$arc1="......................";
$seq2="GGABBBMEMJACBBDMQNPMDK";
$arc2="......................";
$matfile="./SM/BLOSUM-like_scoring_matrix";
$opp="0";
$exp="-1";
$suboptimal="1";
?>
