<?
$seq1 = "GGABBBMEMJACBBDMQNPMDKABAAAABAAGCDJBCACBAAABAAEXKPBCBBADJARJMFBBABCBBAABCQCGG";
$seq2 = "CCECBAMEMJACEGCMQNPMQOSLGFBCABABBMMIMCBFBABBBAHPBCESKQABBCELPACBBCDJFRJMFBAABABBBCBLRLNN";
$matfile = "./SM/BLOSUM-like_scoring_matrix";
$opp = "-8";
$exp = "-5";
$suboptimal = "10";
?>