<?
$seq1 = "AABABAQADJFCBAKRGMOSAIDFGABBBACDJFAACAAABBAMSDVPBABACCJFGJMFBABBABABBAHKLHH";
$seq2 = "GGABBBMEMJACBBDMQNPMDKABAAAABAAGCDJBCACBAAABAAEXKPBCBBADJARJMFBBABCBBAABCQCGG";
$matfile = "./SM/BLOSUM-like_scoring_matrix";
$opp = "0";
$exp = "-1";
$suboptimal = "10";
?>
