<?
$seq1 = "MMSNBABBCAEGAABBABAKIDTCABQTGBBBBAALCCABBABBAAACJADABBBBAAACAMCMOSPCIFAAAAHKXCEMRQSRNTACBAABBCEHVGCBBACEDBABBAAABECGAAAAAIFCBABABBADOOLFABBABBABINGBAHACCABCC";
$seq2 = "DJIDCB";
$matfile = "./SM/BLOSUM-like_scoring_matrix";
$opp = "-6";
$exp = "-1";
$suboptimal = "10";
?>