<?php
$seq1="uuYAC'3JPxXwYuZBZw''xXX";
$arc1="((((((...........))))))";
$seq2="**'uX)6D29'uXCXAXAuXCC)";
$arc2="...((((.........))))...";
$matfile="SM/23-4L_matrix";
$opp="-9";
$exp="-1";
$suboptimal="1";
?>
